name: Generate Verifier JSON

on:
  workflow_dispatch:
    inputs:
      contract_path:
        description: 'مسیر فایل قرارداد (مثال: contracts/MainContract.sol)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Standard Input JSON
        run: python scripts/generate_verification_json.py ${{ github.event.inputs.contract_path }}

      # --- تغییر اصلی در این بخش است ---
      # به جای یک فایل، کل پوشه خروجی را آپلود می‌کنیم
      - name: Upload Verification JSON folder
        uses: actions/upload-artifact@v4
        with:
          name: verification-files
          path: verify-explorer-output/
