name: Generate Verifier JSON and Commit

on:
  workflow_dispatch:
    inputs:
      contract_path:
        description: 'The path to the contract file (e.g., contracts/MainContract.sol)'
        required: true
        type: string

# This new section grants the necessary permissions for the job to push code
permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install required libraries
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run the script to create the JSON file
      - name: Generate Standard Input JSON
        run: python scripts/generate_verification_json.py ${{ github.event.inputs.contract_path }}

      # 5. Commit and push the new files to the repository
      - name: Commit and Push new files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add verify-explorer-output/
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "chore: Generate verifier JSON for ${{ github.event.inputs.contract_path }}"
            git push
          else
            echo "No new verification files to commit."
          fi
